### ISSUE TITLE
Making use of output vectors

### ISSUE THREAD

**Issue by jpillora** [alexandres/lexvec#1]
Sorry if this is a silly question, though can you provide any references to assist in making use of these output vectors in Go?

**Comment by alexandres** [comment]
Have a look at https://github.com/sshillo/word2vec/blob/master/word2vec.go . Though I haven't tested it, it implements model loading and nearest neighbor lookups. You'd need to modify line 41 to read text floats instead of binary data as LexVec only saves vectors in text format. 

If there's interest, I can implement a small-ish Go library for using the vectors (loading, vector similarity, and nearest neighbors) and host it in the LexVec repo.

**Comment by jojo05** [comment]
+1 for the vector utils

**Comment by shul** [comment]
+1 for the vector utils

**Comment by alexandres** [comment]
Another option is https://github.com/bountylabs/lexvec/tree/master/lexvecutil for loading the subword models.
