### ISSUE TITLE
segfault when merging context vectors

### ISSUE THREAD

**Issue by renjithravindran** [alexandres/lexvec#8]
got this error with model=2.
can i get model=2 vectors by the outputs produced in model=0, i.e by adding position context vectors to get W_hat_pos and then add to W?
------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4ca33f]

goroutine 1 [running]:
main.mergeContextVectors()
       .../lexvec/model.go:117 +0x15f
main.saveVectors()
        .../lexvec/model.go:65 +0x455
main.main()
       .../lexvec/main.go:211 +0x13ef

**Comment by alexandres** [comment]
Hi @renjithravindran !

Thank you for catching this. I've fixed this issue in the latest commit. 

I also added this [little script](https://github.com/alexandres/lexvec/blob/master/scripts/merge_context_vectors.py) which we use for our experiments that can do the merging after training. This way you can compare using only word vectors or using merged word and context vectors with a single training run. Just make sure you pass `-model 0` as an argument so that both word and context vectors are saved.
